//
// auto-generated by op2-clang
//

// header
#include "op_lib_cpp.h"
#include "op_cuda_rt_support.h"
#include "op_cuda_reduction.h"
#include "op_cuda_reduction_supp.h"

// global constants
#ifndef MAX_CONST_SIZE
#define MAX_CONST_SIZE 128
#endif

// global constants
double global_var;

void op_decl_const_char(int dim, char const *type, int size, char *dat,
                        char const *name) {
  if (!OP_hybrid_gpu)
    return;
  if (!strcmp(name, "global_var")) {
  }
}

// user kernel files
int include_placeholder;
