//
// auto-generated by op2-clang
//

// header
#include "op_lib_cpp.h"


// global constants
double global_var;

void op_decl_const_char(int dim, char const *type, int size, char *dat,
                        char const *name) {
  if (!strcmp(name, "global_var")) {
  }
}

// user kernel files
int include_placeholder;
